max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
edition = "2021"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
merge_derives = true
use_try = true
warn_on_unreachable_pub = true