target = "x86_64-unknown-linux-gnu"

[tool.cargo-deny]
version = 2

[[tool.cargo-deny.lints]]
name = "unreachable_pub"
level = "warn"

[[tool.cargo-deny.lints]]
name = "unused_qualifications"
level = "allow"